(() => {
'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const W=960,H=608,T=32,C=30,R=19,$=id=>document.getElementById(id);
const rocks=[{x:354,y:72,w:64,h:96},{x:430,y:315,w:96,h:64},{x:573,y:188,w:64,h:64},{x:278,y:456,w:96,h:64},{x:650,y:418,w:64,h:64}];
let g,last=0,id=1,toastTimer;
const d=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),cap=(v,a,b)=>Math.max(a,Math.min(b,v));
const box=e=>({l:e.x-e.w/2,r:e.x+e.w/2,t:e.y-e.h/2,b:e.y+e.h/2});
const cross=(a,b,p=0)=>a.l<b.r+p&&a.r>b.l-p&&a.t<b.b+p&&a.b>b.t-p;
const alive=e=>e&&e.hp>0;
function toast(t){const n=$('toast');n.textContent=t;n.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('show'),2500);}
function soldier(x,y){return {id:id++,kind:'soldier',x,y,hp:100,max:100,speed:90,range:115,damage:23,cd:0,path:[],target:null,repath:0};}
function enemy(x,y,kind){let turret=kind==='turret';return {id:id++,kind,x,y,hp:turret?140:100,max:turret?140:100,speed:turret?0:22,range:turret?132:100,damage:turret?9:5,cd:0,path:[],repath:0};}
function mode(m){g.mode=m;g.placing=false;for(const v of ['select','move','attack'])$(v+'-btn').classList.toggle('active',v===m);$('action-help').textContent=m==='move'?'点地图，让选中步兵移动。':m==='attack'?'点中立目标，让步兵攻击。':'点击建筑或步兵进行选择。';$('map-hint').textContent=m==='select'?'选择基地，再建造兵营':m==='move'?'移动指令待命':'攻击指令待命';}
function reset(){id=1;g={credits:470,state:'playing',paused:false,mode:'select',placing:false,pointer:null,drag:null,selection:[],effects:[],killed:0,total:5,hq:{id:id++,kind:'hq',x:120,y:304,w:88,h:88,hp:1200,max:1200},barracks:[],soldiers:[],enemies:[enemy(783,110,'turret'),enemy(840,295,'turret'),enemy(792,520,'turret'),enemy(695,250,'drone'),enemy(730,395,'drone')]};$('overlay').classList.add('hidden');$('pause-btn').textContent='暂停';mode('select');hud();toast('建造兵营，生产步兵，清除中立阵地');}
function buildings(){return [g.hq,...g.barracks].filter(alive);}
function blocked(cx,cy){if(cx<0||cy<0||cx>=C||cy>=R)return true;let x=cx*T+16,y=cy*T+16,p={l:x-8,r:x+8,t:y-8,b:y+8};return rocks.some(r=>cross(p,{l:r.x,r:r.x+r.w,t:r.y,b:r.y+r.h}))||buildings().some(b=>cross(p,box(b)));}
function freeCell(x,y){let best=null,score=Infinity;for(let j=0;j<R;j++)for(let i=0;i<C;i++){if(blocked(i,j))continue;let z=(i*T+16-x)**2+(j*T+16-y)**2;if(z<score){score=z;best={i,j};}}return best;}
function path(x,y,tx,ty){let a=freeCell(x,y),b=freeCell(tx,ty);if(!a||!b)return [];let key=(i,j)=>j*C+i,start=key(a.i,a.j),goal=key(b.i,b.j),prev=new Int16Array(C*R),q=[start],head=0;prev.fill(-1);prev[start]=start;while(head<q.length){let n=q[head++];if(n===goal)break;let cx=n%C,cy=Math.floor(n/C);for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){let nx=cx+dx,ny=cy+dy;if(blocked(nx,ny))continue;let k=key(nx,ny);if(prev[k]!==-1)continue;prev[k]=n;q.push(k);}}if(prev[goal]===-1)return [];let out=[],n=goal;while(n!==start){out.push({x:n%C*T+16,y:Math.floor(n/C)*T+16});n=prev[n];}return out.reverse();}
function walk(e,dt){if(!e.path.length)return;let p=e.path[0],dx=p.x-e.x,dy=p.y-e.y,l=Math.hypot(dx,dy);if(l<3){e.path.shift();return;}let v=Math.min(l,e.speed*dt);e.x=cap(e.x+dx/l*v,10,W-10);e.y=cap(e.y+dy/l*v,10,H-10);}
function buildOK(x,y){let p={l:x-32,r:x+32,t:y-32,b:y+32};if(p.l<16||p.r>W-16||p.t<16||p.b>H-16)return false;return !rocks.some(r=>cross(p,{l:r.x,r:r.x+r.w,t:r.y,b:r.y+r.h},12))&&!buildings().some(b=>cross(p,box(b),18))&&!g.enemies.some(e=>cross(p,{l:e.x-18,r:e.x+18,t:e.y-18,b:e.y+18},12));}
function snap(p){return {x:Math.round(p.x/T)*T,y:Math.round(p.y/T)*T};}
function startBuild(){if(g.state!=='playing'||g.paused)return;if(g.credits<180){toast('资源不足：兵营需要 180');return;}mode('select');g.placing=true;$('action-help').textContent='点空地放置兵营；右键或 Esc 取消。';$('map-hint').textContent='建造模式 / 选择合法位置';}
function place(p){let s=snap(p);if(!buildOK(s.x,s.y)){toast('无法建造：位置被占用或超出地图');return;}if(g.credits<180){toast('资源不足');return;}let b={id:id++,kind:'barracks',x:s.x,y:s.y,w:64,h:64,hp:300,max:300,queue:0,progress:0};g.barracks.push(b);g.credits-=180;g.selection=[b];mode('select');g.effects.push({type:'ring',x:b.x,y:b.y,life:.7,max:.7,color:'#7ce1c2'});toast('兵营建成，点击“生产步兵”');hud();}
function train(){if(g.state!=='playing'||g.paused)return;let b=g.selection.length===1&&g.selection[0].kind==='barracks'?g.selection[0]:null;if(!b){toast('请先选中兵营');return;}if(b.queue>=5){toast('生产队列已满');return;}if(g.credits<70){toast('资源不足：步兵需要 70');return;}g.credits-=70;b.queue++;toast('步兵已加入生产队列');hud();}
function spawn(b){let best=null,score=Infinity;for(let j=0;j<R;j++)for(let i=0;i<C;i++){if(blocked(i,j))continue;let x=i*T+16,y=j*T+16;if(g.soldiers.some(s=>Math.hypot(s.x-x,s.y-y)<27))continue;let v=(x-b.x-64)**2+(y-b.y-16)**2;if(v<score){score=v;best={x,y};}}if(!best)return;let s=soldier(best.x,best.y);g.soldiers.push(s);g.effects.push({type:'ring',x:s.x,y:s.y,life:.5,max:.5,color:'#7ce1c2'});toast('步兵已就绪');}
function choose(m){if(g.state!=='playing'||g.paused)return;if(m!=='select'&&!g.selection.some(e=>e.kind==='soldier'&&alive(e))){toast('请先选择步兵');return;}mode(m);}
function move(p){let group=g.selection.filter(e=>e.kind==='soldier'&&alive(e));if(!group.length){toast('请先选择步兵');return;}group.forEach((s,i)=>{let a=i*2.4,r=i?19*Math.sqrt(i):0,x=cap(p.x+Math.cos(a)*r,12,W-12),y=cap(p.y+Math.sin(a)*r,12,H-12);s.target=null;s.path=path(s.x,s.y,x,y);s.repath=0;});g.effects.push({type:'ring',x:p.x,y:p.y,life:.5,max:.5,color:'#7ce1c2'});mode('select');}
function attack(e){let group=g.selection.filter(v=>v.kind==='soldier'&&alive(v));if(!group.length){toast('请先选择步兵');return;}group.forEach(s=>{s.target=e;s.path=[];s.repath=0;});g.effects.push({type:'ring',x:e.x,y:e.y,life:.6,max:.6,color:'#ef806d'});mode('select');}
function hit(p){for(let i=g.soldiers.length-1;i>=0;i--)if(d(p,g.soldiers[i])<18)return g.soldiers[i];for(let i=g.enemies.length-1;i>=0;i--)if(d(p,g.enemies[i])<(g.enemies[i].kind==='turret'?28:23))return g.enemies[i];for(const b of g.barracks)if(cross({l:p.x,r:p.x,t:p.y,b:p.y},box(b)))return b;if(cross({l:p.x,r:p.x,t:p.y,b:p.y},box(g.hq)))return g.hq;return null;}
function clickMap(p){if(g.state!=='playing'||g.paused)return;if(g.placing){place(p);return;}if(g.mode==='move'){move(p);return;}if(g.mode==='attack'){let e=hit(p);if(e&&g.enemies.includes(e))attack(e);else toast('请点选中立目标');return;}let e=hit(p);g.selection=e?[e]:[];hud();}
function pos(ev){let r=canvas.getBoundingClientRect();return {x:cap((ev.clientX-r.left)*W/r.width,0,W),y:cap((ev.clientY-r.top)*H/r.height,0,H)};}
canvas.addEventListener('pointerdown',ev=>{if(ev.button===2)return;let p=pos(ev);g.pointer=p;if(g.state!=='playing'||g.paused)return;canvas.setPointerCapture(ev.pointerId);g.drag={start:p,end:p,type:ev.pointerType};});
canvas.addEventListener('pointermove',ev=>{g.pointer=pos(ev);if(g.drag)g.drag.end=g.pointer;});
canvas.addEventListener('pointerleave',()=>{if(!g.drag)g.pointer=null;});
canvas.addEventListener('pointerup',ev=>{if(ev.button===2||!g.drag)return;let p=pos(ev),a=g.drag;g.drag=null;if(g.state!=='playing'||g.paused)return;if(!g.placing&&g.mode==='select'&&a.type!=='touch'&&d(a.start,p)>14){let l=Math.min(a.start.x,p.x),r=Math.max(a.start.x,p.x),t=Math.min(a.start.y,p.y),b=Math.max(a.start.y,p.y);g.selection=g.soldiers.filter(s=>s.x>=l&&s.x<=r&&s.y>=t&&s.y<=b);hud();return;}clickMap(p);});
canvas.addEventListener('pointercancel',()=>g.drag=null);
canvas.addEventListener('contextmenu',ev=>{ev.preventDefault();if(g.state!=='playing'||g.paused)return;if(g.placing){mode('select');return;}let p=pos(ev),e=hit(p);if(e&&g.enemies.includes(e))attack(e);else move(p);});
$('build-btn').onclick=startBuild;$('train-btn').onclick=train;for(const m of ['select','move','attack'])$(m+'-btn').onclick=()=>choose(m);
$('pause-btn').onclick=()=>{if(g.state!=='playing')return;g.paused=!g.paused;$('pause-btn').textContent=g.paused?'继续':'暂停';hud();};
$('restart-btn').onclick=reset;$('overlay-restart').onclick=reset;
document.addEventListener('keydown',ev=>{if(ev.key==='Escape'){if(g.placing||g.mode!=='select')mode('select');else g.selection=[];hud();}if(ev.code==='Space'&&!ev.repeat){ev.preventDefault();$('pause-btn').click();}});
function shoot(a,b,color){b.hp=Math.max(0,b.hp-a.damage);a.cd=a.kind==='soldier'?.65:a.kind==='turret'?1.35:1.55;g.effects.push({type:'shot',x:a.x,y:a.y,tx:b.x,ty:b.y,life:.16,max:.16,color});g.effects.push({type:'spark',x:b.x,y:b.y,life:.35,max:.35,color});}
function finish(won){if(g.state!=='playing')return;g.state=won?'victory':'defeat';$('overlay-kicker').textContent=won?'任务完成':'任务失败';$('overlay-title').textContent=won?'作战胜利':'基地失守';$('overlay-text').textContent=won?'所有中立目标已被清除。':'基地被摧毁。重新部署防线，再试一次。';$('overlay').classList.remove('hidden');hud();}
function update(dt){g.credits=Math.min(9999,g.credits+11*dt);for(const b of g.barracks)if(b.queue){b.progress+=dt/2.6;if(b.progress>=1){b.progress=0;b.queue--;spawn(b);}}for(const s of g.soldiers){s.cd=Math.max(0,s.cd-dt);s.repath-=dt;if(s.target&&!alive(s.target)){s.target=null;s.path=[];}if(!s.target){let near=g.enemies.filter(alive).sort((a,b)=>d(s,a)-d(s,b))[0];if(near&&d(s,near)<s.range)s.target=near;}if(s.target){if(d(s,s.target)<=s.range){s.path=[];if(s.cd<=0)shoot(s,s.target,'#9bf4d1');}else if(s.repath<=0){s.path=path(s.x,s.y,s.target.x,s.target.y);s.repath=.7;}}walk(s,dt);}for(const e of g.enemies){e.cd=Math.max(0,e.cd-dt);e.repath-=dt;let near=g.soldiers.filter(alive).sort((a,b)=>d(e,a)-d(e,b))[0],target=near&&d(e,near)<e.range+22?near:g.hq;if(e.kind==='drone'&&d(e,target)>e.range-4){if(e.repath<=0){e.path=path(e.x,e.y,target.x,target.y);e.repath=1.2;}walk(e,dt);}else e.path=[];if(d(e,target)<=e.range&&e.cd<=0)shoot(e,target,'#ff9a72');}let old=g.enemies.length;g.enemies=g.enemies.filter(alive);g.killed+=old-g.enemies.length;g.soldiers=g.soldiers.filter(alive);g.barracks=g.barracks.filter(alive);g.selection=g.selection.filter(alive);for(const f of g.effects)f.life-=dt;g.effects=g.effects.filter(f=>f.life>0);if(g.hq.hp<=0)finish(false);else if(!g.enemies.length)finish(true);hud();}
function hud(){$('credits').textContent=Math.floor(g.credits);$('enemy-count').textContent=g.enemies.length;$('status').textContent=g.state==='victory'?'胜利':g.state==='defeat'?'失败':g.paused?'暂停':'进行中';$('mission-progress').style.width=g.killed/g.total*100+'%';$('mission-text').textContent='已清除 '+g.killed+' / '+g.total;let s=g.selection;if(!s.length){$('selected-name').textContent='未选择';$('selected-info').textContent='点击基地、兵营或步兵查看信息。';$('selected-health').style.width='0%';$('selected-hp').textContent='—';}else if(s.length>1){$('selected-name').textContent=s.length+' 名步兵';$('selected-info').textContent='右键地面移动，右键目标攻击。';let avg=s.reduce((n,e)=>n+e.hp/e.max,0)/s.length;$('selected-health').style.width=avg*100+'%';$('selected-hp').textContent='平均生命值 '+Math.round(avg*100)+'%';}else{let e=s[0];$('selected-name').textContent=({hq:'指挥基地',barracks:'步兵兵营',soldier:'前线步兵',turret:'中立炮塔',drone:'中立巡逻机'})[e.kind];$('selected-info').textContent=e.kind==='barracks'?'生产队列：'+e.queue+' / 5':e.kind==='hq'?'基地每秒产生资源。':e.kind==='soldier'?'可移动并攻击中立目标。':'中立防御目标。';$('selected-health').style.width=e.hp/e.max*100+'%';$('selected-hp').textContent='生命值 '+Math.ceil(e.hp)+' / '+e.max;}let b=s.length===1&&s[0].kind==='barracks'?s[0]:null;$('train-progress').firstElementChild.style.width=b&&b.queue?b.progress*100+'%':'0%';$('build-btn').disabled=g.state!=='playing'||g.paused||g.credits<180;$('train-btn').disabled=g.state!=='playing'||g.paused||!b||b.queue>=5||g.credits<70;}
function bar(x,y,w,v,color){ctx.fillStyle='#081116';ctx.fillRect(x-w/2,y,w,5);ctx.fillStyle=color;ctx.fillRect(x-w/2,y,w*cap(v,0,1),5);}
function ground(){ctx.fillStyle='#1b2b2e';ctx.fillRect(0,0,W,H);for(let y=0;y<R;y++)for(let x=0;x<C;x++){ctx.fillStyle=(x*37+y*61)%11<3?'#203236':'#1c2d30';ctx.fillRect(x*T+1,y*T+1,T-2,T-2);}ctx.strokeStyle='#354b48';ctx.lineWidth=1;for(let x=0;x<=W;x+=T){ctx.beginPath();ctx.moveTo(x+.5,0);ctx.lineTo(x+.5,H);ctx.stroke();}for(let y=0;y<=H;y+=T){ctx.beginPath();ctx.moveTo(0,y+.5);ctx.lineTo(W,y+.5);ctx.stroke();}ctx.fillStyle='#27433e';ctx.fillRect(0,270,W,65);ctx.fillStyle='#19332f';ctx.fillRect(0,291,W,22);for(let i=0;i<36;i++){ctx.fillStyle='#3a5550';ctx.fillRect((i*197+57)%W,(i*113+69)%H,3,2);}for(const r of rocks){ctx.fillStyle='#101c23';ctx.fillRect(r.x+5,r.y+7,r.w,r.h);ctx.fillStyle='#536361';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.fillStyle='#65716c';ctx.fillRect(r.x+4,r.y+4,r.w-12,8);ctx.fillStyle='#394e4d';ctx.fillRect(r.x+8,r.y+20,r.w-18,r.h-29);}}
function drawBuilding(b){let p=box(b),hq=b.kind==='hq';ctx.fillStyle='#08181e';ctx.fillRect(p.l+5,p.t+7,b.w,b.h);ctx.fillStyle=hq?'#36766c':'#397b6d';ctx.fillRect(p.l,p.t,b.w,b.h);ctx.fillStyle='#214e4c';ctx.fillRect(p.l+8,p.t+8,b.w-16,b.h-16);ctx.strokeStyle='#a1eacb';ctx.lineWidth=3;ctx.strokeRect(p.l+5,p.t+5,b.w-10,b.h-10);if(hq){ctx.fillStyle='#8de3c6';ctx.fillRect(b.x-8,b.y-24,16,48);ctx.fillRect(b.x-24,b.y-8,48,16);ctx.fillStyle='#0e3735';ctx.fillRect(b.x-12,b.y-12,24,24);ctx.fillStyle='#c9ffe3';ctx.fillRect(b.x-4,b.y-4,8,8);}else{ctx.fillStyle='#a6ebcc';for(let i=-1;i<=1;i++)ctx.fillRect(b.x-20+i*16,b.y-17,10,10);ctx.fillStyle='#0e3637';ctx.fillRect(b.x-18,b.y+4,36,24);ctx.fillStyle='#f4c56f';ctx.fillRect(b.x-12,b.y+12,24,4);}bar(b.x,p.t-12,b.w,b.hp/b.max,'#7ce1c2');if(g.selection.includes(b)){ctx.strokeStyle='#f3d67d';ctx.lineWidth=2;ctx.strokeRect(p.l-6,p.t-6,b.w+12,b.h+12);}}
function drawSoldier(s){if(g.selection.includes(s)){ctx.strokeStyle='#f4d783';ctx.lineWidth=2;ctx.beginPath();ctx.arc(s.x,s.y,17,0,7);ctx.stroke();}ctx.fillStyle='#0b1c1d';ctx.beginPath();ctx.arc(s.x+2,s.y+3,11,0,7);ctx.fill();ctx.fillStyle='#8ce1c1';ctx.beginPath();ctx.arc(s.x,s.y,9,0,7);ctx.fill();ctx.fillStyle='#2c695c';ctx.fillRect(s.x-5,s.y-5,10,10);ctx.strokeStyle='#d5fff0';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x+12,s.y-6);ctx.stroke();if(s.hp<s.max)bar(s.x,s.y-19,24,s.hp/s.max,'#7ce1c2');}
function drawEnemy(e){let r=e.kind==='turret'?18:13;ctx.fillStyle='#121b22';ctx.beginPath();ctx.arc(e.x+3,e.y+4,r+4,0,7);ctx.fill();ctx.fillStyle=e.kind==='turret'?'#8d5952':'#9e6a4d';ctx.beginPath();ctx.arc(e.x,e.y,r,0,7);ctx.fill();ctx.strokeStyle='#ffb17a';ctx.lineWidth=3;ctx.beginPath();ctx.arc(e.x,e.y,r-5,0,7);ctx.stroke();ctx.fillStyle='#412d2c';ctx.fillRect(e.x-6,e.y-6,12,12);ctx.fillStyle='#ffd58e';ctx.fillRect(e.x-2,e.y-2,4,4);if(g.selection.includes(e)){ctx.strokeStyle='#ffe092';ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,r+8,0,7);ctx.stroke();}bar(e.x,e.y-r-13,36,e.hp/e.max,'#ee8b70');}
function draw(){ground();for(const b of buildings())drawBuilding(b);for(const e of g.enemies)drawEnemy(e);for(const s of g.soldiers)drawSoldier(s);for(const f of g.effects){let a=f.life/f.max;ctx.globalAlpha=a;ctx.strokeStyle=f.color;ctx.lineWidth=f.type==='shot'?3:2;ctx.beginPath();if(f.type==='shot'){ctx.moveTo(f.x,f.y);ctx.lineTo(f.tx,f.ty);}else ctx.arc(f.x,f.y,8+(1-a)*25,0,7);ctx.stroke();}ctx.globalAlpha=1;if(g.placing&&g.pointer){let p=snap(g.pointer),ok=buildOK(p.x,p.y);ctx.fillStyle=ok?'#7ce1c266':'#ff696966';ctx.fillRect(p.x-32,p.y-32,64,64);ctx.strokeStyle=ok?'#9effd4':'#ff8c80';ctx.lineWidth=2;ctx.strokeRect(p.x-32,p.y-32,64,64);}if(g.drag&&g.drag.type!=='touch'&&g.mode==='select'&&!g.placing){let a=g.drag.start,b=g.drag.end;ctx.fillStyle='#9ce9d322';ctx.strokeStyle='#a9f4dc';ctx.lineWidth=1;ctx.fillRect(Math.min(a.x,b.x),Math.min(a.y,b.y),Math.abs(b.x-a.x),Math.abs(b.y-a.y));ctx.strokeRect(Math.min(a.x,b.x),Math.min(a.y,b.y),Math.abs(b.x-a.x),Math.abs(b.y-a.y));}if(g.paused){ctx.fillStyle='#061116aa';ctx.fillRect(0,0,W,H);ctx.fillStyle='#e8f9f0';ctx.font='bold 42px sans-serif';ctx.textAlign='center';ctx.fillText('已暂停',W/2,H/2);}}
function frame(t){let dt=Math.min(.05,Math.max(0,(t-last)/1000));last=t;if(g.state==='playing'&&!g.paused)update(dt);draw();requestAnimationFrame(frame);}reset();requestAnimationFrame(frame);
})();
